# Generated by Django 2.2.5 on 2019-10-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_auto_20191010_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='media/user_profile.jpeg', upload_to=''),
        ),
    ]
